name: Build and Run Python App

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Or use windows-latest for a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements file

    - name: Run Python app
      run: |
        python main.py  # Run the main.py script to generate the errors
